name = "joolab-bigdata-clean"
compatibility_date = "2026-01-30"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "joolab_bigdata_clean"
database_id = "REPLACE_WITH_YOUR_D1_ID"
